Matt/java backend
AuburnACM/auacm pull request #122
Opened 2017-09-28 05:10 UTC by mmmvvvbbb

I don't think the protobuf is working.

2017-09-29 15:45 UTC, Mac-Genius requested changes
Just change Integer to int. Everything else looks good and the problems populate on the problems page.

2017-09-29 15:45 UTC, Mac-Genius commented on src/main/java/com/auacm/database/model/Problem.java
> +    private Integer competitionId;
If you can, leave this as an int.

2017-09-29 15:45 UTC, Mac-Genius commented on src/main/java/com/auacm/database/model/Problem.java
> +    public Integer getCompetitionId() {
Use int if you can.

2017-09-29 15:45 UTC, Mac-Genius commented on src/main/java/com/auacm/database/model/Problem.java
> +    public void setCompetitionId(Integer competitionId) {
Int please.

2017-09-29 15:45 UTC, Mac-Genius commented on src/main/java/com/auacm/database/model/ProblemData.java
> +    private Integer timeLimit;
Int here as well.

2017-09-30 06:02 UTC, mmmvvvbbb commented
`competitionId` cannot be an int as long as there are null values in the database. I'm not sure how to change the default database from null to something more fitting like 0.

2017-09-30 14:46 UTC, Mac-Genius commented
Alright, we can leave it as Integer for now then.

2017-10-02 01:21 UTC, Mac-Genius approved these changes

2017-10-04 15:50 UTC, merged